docs: fromjson mask
CGI-FR/PIMO pull request #115
Opened 2022-04-19 10:36 UTC by giraud10

2022-04-29 09:46 UTC, youen requested changes

2022-04-29 09:46 UTC, youen commented on README.md
> +  * [`fromjson`](#fromjson) is to change the format of a field to float64.
```suggestion
  * [`fromjson`](#fromjson) is to convert string field values to parsed JSON, e.g. "[1,2,3]" -> [1,2,3].
```

2022-04-29 09:46 UTC, youen commented on README.md
> +This example will mask the `targetfield` field of the input jsonlines with the field `sourcefield` of the jsonline. This mask changes the type of the input string (`sourcefield`) to output float64 (`
```suggestion
This example will mask the `targetfield` field of the input jsonlines with the parsed JSON from  field `sourcefield` of the jsonline. This mask changes the type of the input string (`sourcefield`) : 
 * null : nil
 * string: string
 * number: float64
 * array:  slice
 * object: map
 * bool: bool
```

2022-05-09 08:29 UTC, adrienaury approved these changes

2022-05-14 08:11 UTC, merged