feat: set seed from command line argument
CGI-FR/PIMO pull request #191
Opened 2022-12-08 10:34 UTC by giraud10

2022-12-09 10:36 UTC, adrienaury requested changes
Corriger les problèmes de mise en forme du Markdown

2022-12-09 17:55 UTC, adrienaury requested changes

2022-12-09 17:55 UTC, adrienaury commented on README.md
> -
You should keep the last LF character, it is good practice (for diff readability when adding new line at the end of a file)

2022-12-09 22:28 UTC, youen requested changes

2022-12-09 22:28 UTC, youen commented on cmd/pimo/main.go
> +	case seedValue == 0:
Pourquoi un cas particulier sur le 0? On peut laisser la fonction actuelle de pimo gérer le 0. Ça éviterait de faire de la duplication de code.

2022-12-12 10:04 UTC, giraud10 commented on cmd/pimo/main.go
> +	case seedValue == 0:
pimo gère le 0 au moment de la lecture du masking (donc il gère le 0 que s'il est définit dans le masking) sauf que dans notre cas on veut remplacer la seed du masking par 0 (avec la ligne de commande) donc c'est pour ça que je traite ce cas après.

2022-12-12 10:49 UTC, adrienaury commented on cmd/pimo/main.go
> +	case seedValue == 0:
Effectivement, c'est géré ici : https://github.com/CGI-FR/PIMO/blob/c7961b3b906386e11e0691f4375541a575928003/pkg/model/pipeline.go#L197

Est ce que cela mériterait un petit refactoring @youen pour sortir ce code de la fonction load from file ?

2022-12-13 12:50 UTC, adrienaury approved these changes

2023-02-03 01:33 UTC, merged